# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Tagged Images"
client_id = "08267a137ead223d3dedfc4fe9f6c466"
application_url = "https://scenes-hobbies-cars-encouraged.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://scenes-hobbies-cars-encouraged.trycloudflare.com/auth/callback",
  "https://scenes-hobbies-cars-encouraged.trycloudflare.com/auth/shopify/callback",
  "https://scenes-hobbies-cars-encouraged.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-07"

[pos]
embedded = false

[app_preferences]
url = "https://tagged-images.jumplink.eu/preferences"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tagged-images-demo.myshopify.com"
